package UserCreditionals;

import javax.swing.*;

/**
 *
 * @author phani
 */
public class WalletAmount extends javax.swing.JFrame {

     /**
      * Creates new form WalletAmount
      */
     public WalletAmount() {
          initComponents();
     }

     /**
      * This method is called from within the constructor to initialize the form.
      * WARNING: Do NOT modify this code. The content of this method is always
      * regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">
     private void initComponents() {

          jLabel1 = new javax.swing.JLabel();
          BACK = new javax.swing.JButton();
          jLabel2 = new javax.swing.JLabel();
          Amount = new javax.swing.JTextField();
          ENTER = new javax.swing.JButton();
          jLabel3 = new javax.swing.JLabel();
          MobileNUmber = new javax.swing.JTextField();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
          jLabel1.setText("WALLET AMOUNT");

          BACK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arrow_back_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
          BACK.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BACKActionPerformed(evt);
               }
          });

          jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
          jLabel2.setText("ENTER AMOUNT");

          ENTER.setText("ENTER");
          ENTER.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ENTERActionPerformed(evt);
               }
          });

          jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
          jLabel3.setText("MobileNumber");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                      .addGap(85, 85, 85)
                                                                      .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createSequentialGroup()
                                                                      .addGap(44, 44, 44)
                                                                      .addComponent(BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                  .addComponent(Amount, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                                  .addComponent(MobileNUmber))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 591, Short.MAX_VALUE)
                                        .addComponent(ENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(430, 430, 430))
          );
          layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(BACK, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(90, 90, 90)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                  .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addComponent(MobileNUmber, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)
                                        .addComponent(ENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(202, Short.MAX_VALUE))
          );

          pack();
     }// </editor-fold>

     private void BACKActionPerformed(java.awt.event.ActionEvent evt)
     {
          TransferMoney tm = new TransferMoney() ;
          tm.setVisible(true) ;
          this.dispose() ;
     }

     private void ENTERActionPerformed(java.awt.event.ActionEvent evt)
     {
          dbms d = new dbms() ;
          String amount = d.WalletBalance() ;
          int amt = Integer.parseInt(amount) ;
          int entered = Integer.parseInt(Amount.getText()) ;
          if(entered<=amt)
          {
               AccountMoneyTransfer am = new AccountMoneyTransfer(MobileNUmber.getText(),amount,String.valueOf(entered)) ;
               am.WalletTransfer() ;
               Successfull sc = new Successfull() ;
               sc.setVisible(true) ;
               this.dispose() ;
          }
          else
          {
               JOptionPane.showMessageDialog(this,"Insufficient Balance in Wallet");
          }
     }
     // Variables declaration - do not modify
     private javax.swing.JTextField Amount;
     private javax.swing.JButton BACK;
     private javax.swing.JButton ENTER;
     private javax.swing.JTextField MobileNUmber;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     // End of variables declaration
}